---
addons:
  ssh_known_hosts: "51.254.121.242"
before_deploy:
  - "openssl aes-256-cbc -K $encrypted_36d8d61cfa6b_key -iv $encrypted_36d8d61cfa6b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d"
  - "eval \"$(ssh-agent -s)\""
  - "chmod 400 /tmp/deploy_rsa"
  - "ssh-add /tmp/deploy_rsa"
  - "scp $TRAVIS_BUILD_DIR/target/air-pollution-crawler-1.0-SNAPSHOT-shaded.jar"
deploy:
  provider: script
  script: "golechwi@51.254.121.242:build ssh golechwi@51.254.121.242 '/home/golechwi/run.sh'"
  skip_cleanup: true
  true:
    branch: master
jdk:
  - oraclejdk8
language: java
script:
  - "mvn clean install package"
